#cloud-config
autoinstall:
  version: 1
  apt:
    disable_components: []
    fallback: abort
    geoip: true
    mirror-selection:
      primary:
      - country-mirror
      - arches: &id001
        - amd64
        - i386
        uri: http://archive.ubuntu.com/ubuntu/
      - arches: &id002
        - s390x
        - arm64
        - armhf
        - powerpc
        - ppc64el
        - riscv64
        uri: http://ports.ubuntu.com/ubuntu-ports
    preserve_sources_list: false
    security:
    - arches: *id001
      uri: http://security.ubuntu.com/ubuntu/
    - arches: *id002
      uri: http://ports.ubuntu.com/ubuntu-ports
  codecs:
    install: true
  drivers:
    install: true
  identity:
    hostname: unassigned-host
    password: $6$v52enSs7jI87N9Gt$DkK.s2p.YQTj5Oq9cmxFKmBkobQo5G7hJCZNSSjoGqlBm6i7baLHIJUnO2SEqN7dj5aH1WKyVJCf7P/f0V9LL1
    realname: IS Support
    username: helpdesk_local
  kernel:
    package: linux-generic-hwe-22.04
  keyboard:
    layout: us
    toggle: null
    variant: ''
  locale: en_US.UTF-8
  network:
    version: 2
    ethernets:
      all:  # Use 'all' to specify DHCP for all network interfaces
        dhcp4: true
    wifis: {}
  oem:
    install: auto  source:
    id: ubuntu-desktop
    search_drivers: true
  ssh:
    allow-pw: true
    authorized-keys: []
    install-server: True
  storage:
  config:
  - ptable: gpt
    path: /dev/nvme0n1
    wipe: superblock-recursive
    preserve: false
    name: ''
    grub_device: false
    id: disk-nvme0n1
    type: disk
  - device: disk-nvme0n1
    wipe: superblock
    flag: boot
    number: 1
    preserve: false
    grub_device: true
    offset: 1048576
    path: /dev/nvme0n1p1
    id: partition-0
    type: partition
  - fstype: fat32
    volume: partition-0
    preserve: false
    id: format-0
    type: format
  - device: disk-nvme0n1
    wipe: superblock
    number: 2
    preserve: false
    offset: 1128267776
    path: /dev/nvme0n1p2
    id: partition-1
    type: partition
  - fstype: ext4
    volume: partition-1
    preserve: false
    id: format-1
    type: format
  - device: disk-nvme0n1
    wipe: superblock
    number: 3
    preserve: false
    offset: 3275751424
    path: /dev/nvme0n1p3
    id: partition-2
    type: partition
  - volume: partition-2
    keyfile: /tmp/luks-key-we81uyj9
    recovery_keyfile: null
    path: /dev/mapper/dm_crypt-0
    preserve: false
    id: dm_crypt-0
    type: dm_crypt
  - name: ubuntu-vg
    devices:
    - dm_crypt-0
    preserve: false
    id: lvm_volgroup-0
    type: lvm_volgroup
  - name: ubuntu-lv
    volgroup: lvm_volgroup-0
    wipe: superblock
    preserve: false
    path: /dev/ubuntu-vg/ubuntu-lv
    id: lvm_partition-0
    type: lvm_partition
  - fstype: ext4
    volume: lvm_partition-0
    preserve: false
    id: format-2
    type: format
  - path: /
    device: format-2
    id: mount-2
    type: mount
  - path: /boot
    device: format-1
    id: mount-1
    type: mount
  - path: /boot/efi
    device: format-0
    id: mount-0
    type: mount

  timezone: Europe/Berlin
  updates: security
  version: 1
